# Generated by Django 3.0.3 on 2020-02-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200206_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='name',
            field=models.CharField(default='Standard', max_length=128),
            preserve_default=False,
        ),
    ]
