language: python
python:
- 3.6
before_install:
- pip install poetry
install:
- poetry install
script:
- make test
before_deploy:
- make build
- pip install twine wheel
deploy:
  provider: script
  script: make release
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: b5/5PPViqcGPISI+g8Z+BAPnMjJAeyjgQk8sttGeO6IZXtqK5gyHYoXDuaZSpEZk1/RHa+ZoOYb3LBSxlbZ+IlUhLouun/TOOciKbnO65lCMWAbfZxLkASugrNARYANl0dnDftMaloa4gf0THORu3eUQugxR81J2y018fhaepZ9WRmFTlcUekLXjB/xm7aobfXMQ6bV+fLNgVxiHUDgd9bSDk77ugI1h2pNet1yG0HgWFt0xRef30WpzDa+ja8/e1/I+Pps1Snm73V1vvtJBCt/LNupLAp3lljFQaN3YGgn7qD3jt0N5aLheh2x4RsCIe63hJolm/NenF0pC952UNMBqGUPGGzSNyB/37eqIlyF69h/HzWF6iCx1CFN6TNWEif+9cCRUbY8QrFG0VN+ZQrfs/M956btewpcsdVbGCkxXjJ4xgH9swgLsrjVkshoXbkY4qLjPav172ec9PRngqyBUnBlGGfWBxVjjy4Qb3m4MfSHY3Dtfsb9wNztc2GkOwkpDhfhEnf1ORj0qy7Q/Y4Vl145V+8qB9wWfN48Lxv8nxjbBgumzPglNCBn7qPpz2QxlCSd5q4LwQ7UKvJCAvDuiFYZAQ9xOIsoEVNLNBR7BvRqNXw7yCrkNVy6ijKxobV7uAoMNBTE/yNVOi4Mk20ov7Agaw3bkOCdVzYM99dA=
  - secure: HwlWrswvkMXySMRRxHG7E1fBVJPLvbVWu5GF77zNtJ45MgN123RBi0Ttqt6f+Bko4kxnLhJ6dMSvYlL4mP6u/nPFTrw6D109IqTHvNhPnK7DzROz3YmdiDmgH36w5oaV4jzCD+/bXnQuE9vNFK7wc9JtHdWhEGhRDyZiXVWiO17OZoHcT1aKV626npWLoyHQDFEDkFzme3I3AfzV5dxL94vyvKcTXB3wir7/jCPJj048iDZPLqNgxu9uC5sUqslUCr02z7gbcHsyAHohEFLxxzf7DsVthzHr5HXMUsK9+Ck3we07R4dT4vDr5Bk2KsQ2Y+OjT0RfKgsCH2LX6K85/McWvtgiesksT/ccQTOQ/ZJwuuRVfSW7YpAxvWAQ4dhx8/slwkSK65mq9f/nLlY2Z7Tglrjt2r3gZY9r8QSuJzlxm5O3U2PtmrgGSVDwI86ToObWS1DqwPtYG9/h8RuORiVUj1RZvebb/cz9AWmpLEDGRg5RZBWNKIeWjCNxwV8YcOLX//t5nQeBGRmwTzEDMZv22qUIGrdBU86yjqDEousFPigeOKXqKsTklpfUU17TWt1QxF7ds62P+ZkYyxWdtcPhWKAyUB9/1mSJFcYQzoIC++YHWaUDY0xgWJx2vXFFq7+vwmsCmxtOZmJsQIv0sEWbTQkuFveOPjKrFvP1RFs=
