# Generated by Django 3.0.3 on 2020-02-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopedpermission',
            name='exclude',
            field=models.BooleanField(default=False, help_text="Whether this should be an exclusive permission, meaning that if scope is 'user:update' and exclude is True then users with this usertype will not be able to update users, even their own."),
        ),
    ]
