# Generated by Django 3.0.3 on 2020-02-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_scopedpermission_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopedpermission',
            name='scope',
            field=models.TextField(),
        ),
    ]
