# Generated by Django 3.0.3 on 2020-02-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_auto_20200210_1558'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scopedpermission',
            unique_together={('scope', 'exclude')},
        ),
    ]
