# Generated by Django 3.0.3 on 2020-02-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_auto_20200211_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopedpermission',
            name='exact',
            field=models.BooleanField(default=False, help_text='If checked, the permission needs an exact match to count. In other words, it does not work recursively as standard scoped permissions.'),
        ),
    ]
