# Generated by Django 3.0.3 on 2020-02-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_scopedpermission_exact'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scopedpermission',
            unique_together={('scope', 'exclude', 'exact')},
        ),
    ]
