# Generated by Django 5.0.6 on 2024-07-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_scoped_permissions", "0002_scopedpermissiongroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scopedpermissiongroup",
            name="scoped_permissions",
        ),
        migrations.CreateModel(
            name="StoredScopedPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.TextField()),
                ("verb", models.TextField(blank=True, null=True)),
                (
                    "is_negation",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this should be a negation, meaning that if scope is 'user:update' and is_negation is True then users with this usertype will not be able to update users, even their own.",
                    ),
                ),
                (
                    "is_exact",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, the permission needs an exact match to count. In other words, it does not work recursively as standard scoped permissions.",
                    ),
                ),
            ],
            options={
                "unique_together": {("scope", "verb", "is_negation", "is_exact")},
            },
        ),
        migrations.DeleteModel(
            name="ScopedPermission",
        ),
        migrations.DeleteModel(
            name="ScopedPermissionGroup",
        ),
    ]
